server:
  port: 8081

spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/